### ISSUE TITLE
Swagger Editor Issues

### ISSUE THREAD

**Issue by darrindickey** [cezarykluczynski/stapi#47] opened 2023-04-25 02:39 UTC
The Swagger Editor is displaying an error on the right side of the page and mock API server data on the left for a pet store. the STAPI.yaml file appears to be OK.

**Comment by cezarykluczynski** [comment] 2023-04-25 17:21
Hi, @darrindickey. Could you share more details about your exact steps? Is it a particular version of  STAPI's OpenAPI spec that you are using? Is it a different version of Swagger Editor? Could you provide a screenshot or an error message?

I tried loading [this URL](https://editor.swagger.io/?url=https://stapi.co/api/v1/rest/common/download/stapi.yaml) in several browsers on Windows, Linux and mobile, and there were no errors. Granted, it loads for about 3 seconds, because this YAML file is quite big, and then it's frozen for additional 2 seconds, but after that it is usable without errors. On one occassion I saw a wall of errors on the right for a second, but it all cleared up. I also tried with [new version of the editor](https://editor-next.swagger.io/), pasting specs content on the left this time, and there were no errors.

**Comment by darrindickey** [comment] 2023-04-25 21:04
Yes. I was on stapi.co and from this page.
[image: image.png]

I clicked the Swagger Editor link in the text which links to this address:
https://editor.swagger.io/?url=http://stapi.co/api/v1/rest/common/download/stapi.yaml

And I get this page:
[image: image.png]

Darrin

**Comment by cezarykluczynski** [comment] 2023-04-26 16:19
@darrindickey I'm afraid the images you were attaching via email did not make it to GitHub. Could you add them directly in GitHub comment?

**Comment by darrindickey** [comment] 2023-04-26 18:23
@cezarykluczynski, I have updated my earlier comment to include links to the images.

**Comment by cezarykluczynski** [comment] 2023-04-26 18:40
@darrindickey Thanks, it's clear now and I know what the problem is. It will be fixed in the next release, planned for the middle of May. Until then, you can use [this link](https://editor.swagger.io/?url=https://stapi.co/api/v1/rest/common/download/stapi.yaml) for loading specs. It uses HTTPS, so Swagger Editor will not complain about mixed content issues.

**Closed** 2023-04-26 22:07 UTC
